---
- name: Validating Digital Signature for DB backup volumes
  block:
    - name: Recursively find oss for catalog
      ansible.builtin.find:
        paths: "{{ fss_mount_point }}"
        age: "1d"
#        patterns: "*{{ ansible_date_timee.date }}*"
        recurse: "yes"
#        excludes: "*{{ ansible_date_time.date }}*"
        excludes:
          - "*.tar.gz"
          - "*.sha256"
          - "*_image_*"
          - "daily.cvd.*"
          - "main.cvd.*"
          - "dns_records_*"
          - "lb_tf_*"
      register: "backup_list"

    - debug:
        msg: "{{ item.path|basename }}"
      with_items: "{{ backup_list.files }}"

    - name: Running virus scan on DB backup volume
      delegate_to: 'localhost'
      when: >
        topic_ocid is defined
      shell: 'clamscan -ir "{{ item.path }}" | grep "Infected files" | tr -d " " |awk -F":" "{print $2 }"'
      register: clamav_boot_status
      with_items: "{{ backup_list.files }}"
      failed_when: "'Infectedfiles:0' not in clamav_boot_status.stdout"

    - debug:
        msg: "{{ clamav_boot_status }}"

    - name: Updating log file with Antivirus status
      shell: 'echo "PASS" > {{ err_logs }}/{{ item }}_{{ ansible_date_time.date }}.log'
      with_items:
        - "db_avscan" 

  rescue:
    - name: Updating log file with Antivirus status
      shell: 'echo "FAIL" > {{ err_logs }}/{{ item }}_{{ ansible_date_time.date }}.log'
      with_items:
        - "db_avscan"

    - name: Generating Alert for DB Backup volume AntiVirus Verification failure
      delegate_to: 'localhost'
      when: >
        item.stdout == 'Infectedfiles:1'
      oci_ons_publish_result:
        topic_id: "{{ topic_ocid }}"
        title: "FAILED: DB Backup Anitvirus Validation for {{ item.item.path|basename }}"
        body: "DB Backup Antivirus Validation failed for file {{ item.item.path|basename }} as on date: {{ ansible_date_time.date }}"
      with_items: "{{ clamav_boot_status.results }}"
