---
- name: Cloning Boot Volume Playbook
  connection: local
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: oci-mount-fuse
    - role: oci-digital-signature
