---
- name: Cleanup custom image
  block:
    - name: Collecting custom image facts
      delegate_to: 'localhost'
      oci_compute_image_facts:
        auth_type: "instance_principal"
        compartment_id: "{{ dest_compartment_ocid }}"
        display_name: "{{ inventory_hostname }}"
      register: image_facts

    - name: Deleting old custom image
      delegate_to: 'localhost'
      when: image_facts.images[0].id is defined
      oci_compute_image:
        auth_type: "instance_principal"
        compartment_id: "{{ dest_compartment_ocid }}"
        image_id: "{{ image_facts.images[0].id }}"
        state: "absent"
      register: image_cleanup_status

  rescue:
    - name: Generating Alert for custom image cleanup failed
      delegate_to: 'localhost'
      oci_ons_publish_result:
        auth_type: "instance_principal"
        topic_id: "{{ topic_ocid }}"
        title: "FAILED: Custom Image cleanup {{ inventory_hostname }}"
        body: "Custom image cleanup failed for host {{ inventory_hostname }}"

