---
- name: Restore, validate & notify
  hosts: cyber_database
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
   - name: wait_for_connection
     wait_for_connection:
       delay: 5
       timeout: 600
  roles:
   - role: oci-restore-database
